/* data.js — the chronological dataset the Throughline reads. ONE global,
   classic script — generated by Hope for Arun Ganapathy on 2026-06-11. */
window.HOPE_DATA = {
  "timeline": [
    {
      "id": "btech-nit-calicut",
      "type": "education",
      "date_start": "2016-08",
      "date_end": "2020-05",
      "label": "B.Tech ECE @ NIT Calicut",
      "org": "NIT Calicut",
      "domain": "nitc.ac.in",
      "metric": null,
      "skills": [
        "embedded systems",
        "signal processing"
      ],
      "pane": "education",
      "anchor": "tl-btech-nit-calicut"
    },
    {
      "id": "bass-drum-pedal",
      "type": "project",
      "date_start": "2019-01",
      "date_end": "2020-05",
      "label": "Automatic bass drum pedal",
      "org": "NIT Calicut",
      "domain": "github.com",
      "metric": null,
      "skills": [
        "embedded systems"
      ],
      "pane": "projects",
      "anchor": "tl-bass-drum-pedal"
    },
    {
      "id": "novartis-analyst",
      "type": "experience",
      "date_start": "2020-08",
      "date_end": "2022-07",
      "label": "Analyst → BA @ Novartis",
      "org": "Novartis",
      "domain": "novartis.com",
      "metric": "+10% ROI on US drug portfolios",
      "skills": [
        "optimization",
        "Python",
        "SQL"
      ],
      "pane": "experience",
      "anchor": "tl-novartis-analyst"
    },
    {
      "id": "msba-iowa",
      "type": "education",
      "date_start": "2022-08",
      "date_end": "2024-05",
      "label": "MSBA @ Iowa",
      "org": "University of Iowa",
      "domain": "uiowa.edu",
      "metric": "100% scholarship",
      "skills": [
        "machine learning",
        "statistics"
      ],
      "pane": "education",
      "anchor": "tl-msba-iowa"
    },
    {
      "id": "iowa-research",
      "type": "experience",
      "date_start": "2022-08",
      "date_end": "2024-05",
      "label": "NSF Research Data Scientist",
      "org": "University of Iowa",
      "domain": "uiowa.edu",
      "metric": "700M rows processed",
      "skills": [
        "PySpark",
        "Dask",
        "research"
      ],
      "pane": "experience",
      "anchor": "tl-iowa-research"
    },
    {
      "id": "az-900",
      "type": "certification",
      "date_start": "2023-12",
      "date_end": "2023-12",
      "label": "Azure Fundamentals (AZ-900)",
      "org": "Microsoft",
      "domain": "microsoft.com",
      "metric": null,
      "skills": [
        "Azure cloud"
      ],
      "pane": "certifications",
      "anchor": "tl-az-900"
    },
    {
      "id": "clinical-trial-match",
      "type": "project",
      "date_start": "2024-01",
      "date_end": "2024-12",
      "label": "Clinical-trial matching engine",
      "org": null,
      "domain": "github.com",
      "metric": null,
      "skills": [
        "RAG",
        "NER",
        "Python"
      ],
      "pane": "projects",
      "anchor": "tl-clinical-trial-match"
    },
    {
      "id": "careerx-founder",
      "type": "experience",
      "date_start": "2024-05",
      "date_end": "2024-12",
      "label": "Founder & CTO @ CareerX",
      "org": "CareerX",
      "domain": "careerx.app",
      "metric": "$250K Microsoft backing",
      "skills": [
        "RAG",
        "graph databases",
        "Azure OpenAI"
      ],
      "pane": "experience",
      "anchor": "tl-careerx-founder"
    },
    {
      "id": "ey-lead-ai",
      "type": "experience",
      "date_start": "2025-01",
      "date_end": null,
      "label": "Lead AI Engineer @ EY",
      "org": "EY",
      "domain": "ey.com",
      "metric": "$2M+ pipeline · 5 funded",
      "skills": [
        "multi-agent orchestration",
        "MCP",
        "physical AI"
      ],
      "pane": "experience",
      "anchor": "tl-ey-lead-ai"
    },
    {
      "id": "inspection-platform",
      "type": "project",
      "date_start": "2025-01",
      "date_end": null,
      "label": "Robot inspection platform",
      "org": "EY",
      "domain": null,
      "metric": "$2M+ client pipeline",
      "skills": [
        "physical AI & robotics",
        "ROS2"
      ],
      "pane": "projects",
      "anchor": "tl-inspection-platform"
    },
    {
      "id": "agent-platform",
      "type": "project",
      "date_start": "2025-02",
      "date_end": null,
      "label": "Enterprise agent platform",
      "org": "EY",
      "domain": null,
      "metric": "15+ repos",
      "skills": [
        "LangGraph",
        "Autogen",
        "Kubernetes"
      ],
      "pane": "projects",
      "anchor": "tl-agent-platform"
    },
    {
      "id": "workflow-engine",
      "type": "project",
      "date_start": "2025-02",
      "date_end": "2025-06",
      "label": "Multi-agent workflow engine",
      "org": "EY",
      "domain": null,
      "metric": "3 weeks → 2 days",
      "skills": [
        "Autogen",
        "MCP"
      ],
      "pane": "projects",
      "anchor": "tl-workflow-engine"
    },
    {
      "id": "image-gen-app",
      "type": "project",
      "date_start": "2025-04",
      "date_end": "2025-05",
      "label": "AI image app — 100K users",
      "org": "EY",
      "domain": null,
      "metric": "100K+ users in 11 days",
      "skills": [
        "FastAPI",
        "React"
      ],
      "pane": "projects",
      "anchor": "tl-image-gen-app"
    }
  ],
  "traveler": {"inline": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"currentColor\"><path d=\"M14.6 16.4a4.4 4.4 0 1 1-8.8 0 4.4 4.4 0 1 1 8.8 0ZM15.5 13.4a2.9 2.9 0 1 1-5.8 0 2.9 2.9 0 1 1 5.8 0ZM19.6 3.2l1.2 1.2-7.3 7.3-1.2-1.2ZM19.2 1.5l3.3 3.3-1.4 1.4-3.3-3.3ZM10.5 16.2a1.3 1.3 0 1 0-2.6 0 1.3 1.3 0 1 0 2.6 0Z\"/></svg>"}
};
